# Generated by Django 4.2 on 2023-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=33)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
